### ISSUE TITLE
invalid  link for the syscall2api_dataset.tar.gz file

### ISSUE THREAD

**Issue by pwnmelife** [eurecom-s3/syscall2api#3]
Hello, eurecom-s3:
        My name is pwnmelife. Recently, I am going to reconstruct the windows syscall semantic gap, like your paper, Exploring Syscall-Based Semantics Reconstruction of Android Applications. Therefore, I clone your code from github.com. But, your remote file, syscall2api_dataset.tar.gz, can not be downloaded from your server, and the link is invalid. Please provide the lastest valid link for this file. Thank you.

**Comment by mpuzz** [comment]
hello,
I double-checked, and the link is actually valid.
However, for some reason, chrome cannot carry out the download of the file.
I tried both Firefox and curl and they work just fine.
Let me know if you manage to download the dataset.

**Comment by pwnmelife** [comment]
> hello,
> I double-checked, and the link is actually valid.
> However, for some reason, chrome cannot carry out the download of the file.
> I tried both Firefox and curl and they work just fine.
> Let me know if you manage to download the dataset.

Thank you. It's fine to download the file from the edge browser.

**Comment by pwnmelife** [comment]
Chrome does not support to download the dataset file. Please use the other browsers.
